name: take_same_path
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_launcher_icons: ^0.14.1
  matrices: ^1.2.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/airplane.jpg"
  min_sdk_android: 21

flutter:
  generate: true
  assets: 
        - assets/images/         
        - assets/icons/
  uses-material-design: true
